version: '3.8'
services:
  myspinwheelservice_dev:
    image: us-central1-docker.pkg.dev/access-project-413708/spin-wheel-repo/myspinwheelservice:dev
    build:
      context: myspinwheelservice
    env_file:
      - myspinwheelservice/.env
    ports:
      - "8000:8000"
    container_name: myspinwheelservice_dev_app

