version: '3.8'
services:
  myspinwheelservice_dev:
    image: us-central1-docker.pkg.dev/spin-wheel-439406/spin-wheel-backend/myspinwheelservice:dev
    build:
      context: myspinwheelservice
    env_file:
      - myspinwheelservice/.env
    ports:
      - "8000:8000"
    container_name: myspinwheelservice_dev_app
  myspinwheelservice_local:
    image: spin_wheel_service:dev
    build: 
      context: myspinwheelservice
    env_file:
      - myspinwheelservice/.env
    ports:
      - "8000:8000"
    container_name: myspinwheelservice_local_app
  db:
    image: postgres:13.16
    ports:
      - "5432:5432"
    env_file:
      - myspinwheelservice/.env 
    container_name: test-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
