# Generated by Django 5.1.2 on 2024-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myspinwheelapp', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
